import type { Metadata } from "next";
import "./globals.css";
import Providers from "./theme/Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Providers>
        <body className="dark:bg-gray-900 dark:text-white">{children}</body>
      </Providers>
    </html>
  );
}
