import "./globals.css";

import type {Metadata} from "next";
import {initialState} from "./store/initial-state";
import {StoreProvider} from "./store/provider";
import ThemeProvider from "./theme/providers";
import Header from "./header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="dark:bg-gray-900 dark:text-white">
        <StoreProvider state={initialState}>
          <ThemeProvider>
            <main className="w-screen min-h-screen flex flex-col">
              <Header />
              {children}
            </main>
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
